// ============================================================
// 字典：以简体中文原文为 key。
// 收录全部界面文案；查不到的字符串（用户自定义内容）原样显示。
// 动作名采用健身房通用叫法（日：片假名惯用名；英：标准名）。
// ============================================================

export const DICT_JA: Record<string, string> = {
  // ---- 导航 / 通用 ----
  "今天": "今日",
  "今日": "今日",
  "计划": "プラン",
  "历史": "履歴",
  "数据": "データ",
  "设置": "設定",
  "取消": "キャンセル",
  "删除": "削除",
  "记录": "記録",
  "编辑": "編集",
  "切换": "切替",
  "收起": "閉じる",
  "移除": "削除",
  "上移": "上へ",
  "下移": "下へ",
  "选填": "任意",
  "未设置": "未設定",
  "未分类": "未分類",
  "未记录": "記録なし",
  "未规划": "未設定",
  "已记录": "記録済み",
  "已加入": "追加済み",
  "已启用": "有効",
  "已保存": "保存済み",
  "已清空": "削除しました",
  "已选定": "選択済み",
  "新的一天": "新しい一日",
  "天": "日",
  "组": "セット",
  "次": "回",
  "分": "分",
  "分钟": "分",
  "动作": "種目",
  "其他": "その他",
  "新建": "追加",
  "完成": "完了",
  "复制": "コピー",
  "复制全部计划": "全プランをコピー",
  "已复制": "コピーしました",
  "复制失败，请手动选择": "コピー失敗、手動で選択してください",
  "分享": "シェア",
  "今日卡片": "今日のカード",
  "今天还没有记录": "今日はまだ記録がありません",
  "折叠": "折りたたむ",
  "刷新": "更新",
  "有新版本": "新バージョンあり",

  // ---- 训练类型 ----
  "推": "プッシュ",
  "拉": "プル",
  "腿": "脚",
  "休": "休",
  "休息": "休み",
  "休息日": "休息日",
  "自定义": "カスタム",
  "推日": "プッシュデー",
  "拉日": "プルデー",
  "腿日": "レッグデー",

  // ---- 首页 ----
  "训练": "トレーニング",
  "饮食": "食事",
  "有氧": "有酸素",
  "训练 · TRAINING": "トレーニング · TRAINING",
  "饮食 · NUTRITION": "食事 · NUTRITION",
  "有氧 · CARDIO": "有酸素 · CARDIO",
  "今日状态": "今日のステータス",
  "还未记录": "未記録",
  "选择训练": "種目を選択",
  "已记为休息日": "休息日として記録",
  "点击编辑 →": "タップして編集 →",
  "点击查看 / 再记一条 →": "確認 / 追加で記録 →",
  "待开始": "未開始",
  "还差训练": "トレーニング未記録",
  "还差饮食": "食事未記録",
  "{n} 组完成 · 查看 →": "{n}セット完了 · 確認 →",
  "已完成 {n} 组 · 继续 →": "{n}セット完了 · 続ける →",
  "今日计划 · {s} →": "今日の予定 · {s} →",
  "{n} 组": "{n}セット",
  "进行中": "進行中",
  "开始训练": "トレーニング開始",
  "开始记录": "記録を開始",
  "继续": "続ける",
  "训练已完成": "トレーニング完了",
  "今日已完成": "今日は完了",
  "连续": "連続",
  "记录有氧": "有酸素を記録",
  "沿用上次": "前回を引き継ぐ",
  "已加一组": "1セット追加",

  // ---- 训练页 / 模块 ----
  "补记训练": "過去の記録（トレーニング）",
  "选择今天的训练类型开始记录": "今日のタイプを選んで記録開始",
  "休息日 · 好好恢复": "休息日 · しっかり回復",
  "结束训练": "トレーニング終了",
  "继续记录": "記録を続ける",
  "切到休息日？已记录的 {n} 组会被隐藏": "休息日に切替？記録済みの{n}セットは非表示になります",
  "切到「{t}」？已记录的 {n} 组会保留": "「{t}」に切替？記録済みの{n}セットは保持されます",
  "数据不会删除": "データは削除されません",
  "，切回原类型即可见": "。元のタイプに戻せば表示されます",
  "已套用 {a} · +{n} 动作": "{a}を適用 · +{n}種目",
  "动作已都在": "種目は全て追加済み",
  "编辑模板": "テンプレート編集",
  "· 补记": "· 過去入力",

  // ---- 动作卡 ----
  "主": "メイン",
  "计划 {p}": "目標 {p}",
  "上次": "前回",
  "上次 ": "前回 ",
  "首次记录此动作": "この種目は初記録",
  "空白组": "空のセット",
  "加一组": "セット追加",
  "删除动作": "種目を削除",
  "删除该组": "このセットを削除",
  "删除「{name}」及 {n} 组记录？": "「{name}」と{n}セットの記録を削除？",
  "第{n}组 重量": "{n}セット目 重量",
  "第{n}组 次数": "{n}セット目 回数",
  "减一组": "セットを減らす",

  // ---- 添加动作面板 ----
  "添加动作": "種目を追加",
  "上次也做了": "前回もやった",
  "+ 全部加入": "+ 全て追加",
  "新建动作名称…": "新しい種目名…",
  "选部位": "部位を選択",
  "没有想要的？新建「{m}」动作": "なければ「{m}」の種目を新規作成",
  "动作名称…": "種目名…",
  "已删除": "削除しました",
  "已移到 {m}": "{m}に移動しました",
  "删除后历史记录仍保留，模板里若引用会保留名字但不再按部位归类。": "削除後も履歴は残ります。テンプレートで参照中なら名前は残りますが、部位分類はされません。",
  "点铅笔可改名 / 改部位 / 改器械或删除。删除后历史记录仍保留，只是不再出现在选择器。": "鉛筆で名前・部位・器具の変更や削除ができます。削除後も履歴は残り、選択リストから消えるだけです。",
  "器械（选填）": "器具（任意）",
  "选好部位，这个动作才会计入容量统计、并能按部位找到": "部位を選ぶと、ボリューム集計に反映され、部位から探せます",
  "已有记录，删除请到该动作卡片": "記録あり。削除は種目カードから",

  // ---- 模板 ----
  "训练模板": "トレーニングテンプレート",
  "推 1": "プッシュ 1",
  "推 2": "プッシュ 2",
  "拉 1": "プル 1",
  "拉 2": "プル 2",
  "如：重量向": "例：高重量",
  "如：容量向": "例：ボリューム",
  "如：宽度向": "例：広がり",
  "如：厚度向": "例：厚み",
  "一份即可": "1つで十分",
  "推1 / 推2 / 拉1 / 拉2 / 腿": "プッシュ1 / 2 · プル1 / 2 · 脚",
  "按部位选动作 · 存目标组数×次数 · 训练页一键套用": "部位別に種目選択 · 目標セット×回数を保存 · ワンタップ適用",
  "存动作与目标组数 × 次数，不存重量 —— 重量由「沿用上次」自动跟随": "種目と目標セット×回数を保存。重量は保存せず「前回を引き継ぐ」が自動追従",
  "{n} 动作 · {m} 组": "{n}種目 · {m}セット",
  "{n}/5 已设": "{n}/5 設定済み",
  "还没有动作 —— 从下方按部位添加": "種目なし —— 下の部位から追加",
  "组 ×": "セット ×",
  "按部位加动作": "部位から種目を追加",
  "按部位选择": "部位で選択",
  "这个部位还没有动作": "この部位には種目がありません",

  // ---- 营养 ----
  "营养": "栄養",
  "快速": "クイック",
  "详细": "詳細",
  "热量": "カロリー",
  "蛋白": "タンパク質",
  "碳水": "炭水化物",
  "脂肪": "脂質",
  "补记饮食": "過去の記録（食事）",
  "继承上次 {n} kcal · 一键填入": "前回の{n}kcalを引き継ぐ · ワンタップ入力",
  "复制上次 · {n} kcal": "前回をコピー · {n}kcal",
  "宏量按昨天比例自动估算": "PFCは前回の比率で自動推定",
  "宏量按默认比例估算 · P30/C45/F25": "PFCは既定比率で推定 · P30/C45/F25",
  "输入热量即可，宏量自动生成": "カロリー入力だけでPFC自動生成",
  "宏量推算约 {n} kcal，与录入差距较大（仅提醒）": "PFCからの推定は約{n}kcal。入力値と差が大きい（参考まで）",
  "微调宏量": "PFCを微調整",

  // ---- 有氧 ----
  "补记有氧": "過去の記録（有酸素）",
  "走路": "ウォーキング",
  "跑步": "ランニング",
  "单车": "バイク",
  "椭圆机": "エリプティカル",
  "划船": "ローイング",
  "爬楼梯": "ステアクライマー",
  "跳绳": "縄跳び",
  "自定义方式（如：游泳、爬山）": "カスタム（例：水泳、登山）",
  "时长": "時間",
  "时长（分钟）": "時間（分）",
  "平均心率": "平均心拍数",
  "平均心率（选填）": "平均心拍数（任意）",
  "备注（选填）": "メモ（任意）",
  "平均 {n} bpm": "平均 {n} bpm",
  "已记录有氧": "有酸素を記録しました",
  "填了身体数据后，平均心率可自动判定区间": "身体データを入力すると平均心拍からゾーン自動判定",

  // ---- 心率区间 ----
  "心率区间": "心拍ゾーン",
  "· 选强度": "· 強度を選択",
  "恢复": "回復",
  "有氧基础": "有酸素ベース",
  "节奏": "テンポ",
  "阈值": "閾値",
  "最大": "最大",
  "很轻松，能轻松交谈甚至唱歌": "とても楽。会話も歌も余裕",
  "能完整成句对话 · 燃脂主区": "会話が普通にできる · 脂肪燃焼ゾーン",
  "说话开始断续": "会話が途切れがちになる",
  "只能蹦出几个词 · 间歇": "単語しか出ない · インターバル",
  "几乎说不出话 · 冲刺": "ほぼ話せない · スプリント",
  "凭感觉": "感覚で",
  "填身体数据 →": "身体データを入力 →",
  "区间为参考，非医疗建议": "ゾーンは参考値です。医療アドバイスではありません",
  "填入年龄即可显示你的具体心率区间": "年齢を入力すると具体的な心拍ゾーンを表示",
  "基于实测最大心率 {bpm} + 静息心率（Karvonen）": "実測最大心拍 {bpm} + 安静時心拍（Karvonen）に基づく",
  "基于实测最大心率 {bpm}": "実測最大心拍 {bpm} に基づく",
  "估算最大心率 {bpm} + 静息心率（Karvonen）· 估算值": "推定最大心拍 {bpm} + 安静時心拍（Karvonen）· 推定値",
  "估算最大心率 {bpm}（按年龄）· 个体可差 ±10–12 bpm": "推定最大心拍 {bpm}（年齢から）· 個人差 ±10–12 bpm",

  // ---- 排程 ----
  "训练规划": "トレーニングプラン",
  "每周排程": "週間スケジュール",
  "训练状态": "ステータス",
  "推 / 拉 / 腿 / 休 / 无规划。改动即保存,只是建议,不约束实际训练。": "プッシュ / プル / 脚 / 休 / 未設定。即時保存。あくまで目安で、実際の記録を制限しません。",
  "近 28 天": "直近28日",
  "近 4 周训练 {n} 天,可考虑安排减载(信息提示,不强制)": "直近4週で{n}日トレーニング。デロードの検討を（情報のみ・強制なし）",
  "近 4 周训练 {n} 天 —— 仅作参考,不做训练建议": "直近4週で{n}日トレーニング —— 参考情報のみ",
  "次训练": "回",
  "· 今": "· 今日",
  "一": "月",
  "二": "火",
  "三": "水",
  "四": "木",
  "五": "金",
  "六": "土",
  "日": "日",

  // ---- 历史 ----
  "近 30 天": "直近30日",
  "练": "トレ",
  "无训练": "トレなし",
  "改训练": "トレ編集",
  "改饮食": "食事編集",
  "改有氧": "有酸素編集",
  "有氧 {n}′": "有酸素 {n}分",
  "未标强度 {n} 分钟": "強度未設定 {n}分",

  // ---- 数据页 ----
  "体重": "体重",
  "腰围与体脂": "ウエスト・体脂肪",
  "估算体脂率": "推定体脂肪率",
  "仅作估算": "推定値",
  "先在设置填写生理性别和身高": "設定で生物学的性別と身長を入力してください",
  "记录一条腰围后即可估算": "ウエストを1件記録すると推定できます",
  "前往设置": "設定へ",
  "腰围": "ウエスト",
  "用于 RFM": "RFMに使用",
  "腰高比": "ウエスト身長比",
  "估算脂肪量": "推定脂肪量",
  "估算去脂体重": "推定除脂肪体重",
  "由体重换算": "体重から換算",
  "再记录体重后，可换算估算脂肪量与去脂体重": "体重も記録すると、推定脂肪量と除脂肪体重を換算できます",
  "公式：{formula}。体重仅用于换算脂肪量，不参与体脂公式。": "式：{formula}。体重は脂肪量の換算にのみ使用し、体脂肪率の式には含まれません。",
  "腰围测量标准": "ウエスト測定方法",
  "站立、自然呼气末、皮尺水平贴在裸露腰部右侧髂嵴最高外缘；不勒紧。每次尽量同一时间和位置。": "立位で自然呼気の終わりに、裸の腰の右腸骨稜の最上外側縁でメジャーを水平に当てます。締め付けず、毎回同じ時間・位置で測定してください。",
  "RFM 适用于成人群体估算；肌肉量极高、特殊疾病或测量位置变化时偏差会更大。优先看同一测量方法下的长期趋势。": "RFMは成人向けの推定です。筋量が非常に多い場合、特定の疾患、測定位置の違いでは誤差が大きくなります。同一条件での長期推移を優先してください。",
  "还没有腰围记录": "ウエスト記録なし",
  "腰围趋势图：{range}，共 {n} 条记录": "ウエスト推移：{range}、全{n}件",
  "今日腰围": "今日のウエスト",
  "今日体重": "今日の体重",
  "记录今天": "今日を記録",
  "今天已记录，可覆盖": "今日は記録済み。上書き可",
  "趋势与备份": "推移とバックアップ",
  "本周有氧 · 7 天": "今週の有酸素 · 7日",
  "近期训练": "最近のトレーニング",
  "还没有训练记录": "トレーニング記録なし",
  "本周平均": "今週平均",
  "均线": "平均線",
  "基于 {n} 次": "{n}回に基づく",
  "{n}周前": "{n}週間前",
  "对比": "比較",
  "{n}周前平均": "{n}週間前の平均",
  "该周暂无记录，数据不足以对比": "その週は記録がなく、比較できません",
  "轻了 {n} kg": "{n}kg 減",
  "重了 {n} kg": "{n}kg 増",
  "还没有体重记录": "体重記録なし",
  "近 {n} 次": "直近{n}回",
  "近 {n} 天": "直近{n}日",
  "全部": "すべて",
  "图表范围": "グラフの範囲",
  "点按图表查看": "グラフをタップして確認",
  "{n} 条": "{n}件",
  "体重趋势图：{range}，共 {n} 条记录": "体重推移グラフ：{range}、全{n}件",
  "较上一条": "前回比",
  "首条记录": "最初の記録",
  "查看全部 {n} 条": "全{n}件を表示",
  "收起记录": "記録を折りたたむ",
  "仅显示，不可编辑": "表示のみ。編集不可",

  // ---- 设置 ----
  "偏好 · 数据 · 备份": "設定 · データ · バックアップ",
  "界面模式": "UIモード",
  "默认": "デフォルト",
  "纯工具感": "ピュアツール",
  "更强反馈与节奏感": "強めのフィードバックとリズム",
  "模式只改变视觉与微反馈,不改变数据。随时切换。": "モードは見た目と微フィードバックのみ。データは不変。いつでも切替可。",
  "语言": "言語",
  "身体数据": "身体データ",
  "身高": "身長",
  "生理性别": "生物学的性別",
  "男性": "男性",
  "女性": "女性",
  "身高和生理性别仅用于腰围 RFM 体脂估算，不影响训练建议。": "身長と生物学的性別は、ウエストRFM体脂肪推定にのみ使用し、トレーニング提案には影響しません。",
  "出生年份": "生まれ年",
  "如 2003": "例 2003",
  "静息心率": "安静時心拍",
  "最大心率": "最大心拍",
  "推算最大心率": "推定最大心拍",
  "全部可选 —— 不填也能用谈话测试估区间；填了越多，心率区间越贴你。静息心率：早晨醒来别动，数 1 分钟脉搏。": "全て任意。未入力でもトークテストでゾーン推定可。入力するほど正確に。安静時心拍：朝起きてすぐ動かず1分間脈を数える。",
  "训练水平": "トレーニングレベル",
  "新手": "初心者",
  "中级": "中級者",
  "高级": "上級者",
  "< 1 年": "1年未満",
  "1 – 3 年": "1〜3年",
  "3 年以上": "3年以上",
  "较低容量即可进步，过量反而恢复不来": "少ないボリュームでも成長。やり過ぎは回復不能",
  "需要更高容量维持进步": "成長維持にはより多くのボリュームが必要",
  "接近容量上限，注重质量与恢复": "上限に近い。質と回復を重視",
  "每周每肌群目标": "週あたり筋群ごとの目標",
  "选择训练水平，系统给出适合你的每周容量目标（新手不必硬上大容量）。": "レベルを選ぶと適切な週間ボリューム目標を提示（初心者は大ボリューム不要）。",
  "小肌群（二头/三头/小腿）通常还会从复合动作获得额外间接容量。区间为参考，按恢复情况自行增减。": "小筋群（二頭/三頭/カーフ）は複合種目から間接ボリュームも得ます。目安として回復に応じて調整。",
  "自定义动作": "カスタム種目",
  "确认删除": "削除を確認",
  "删除后,以前记录里的该动作仍然保留(以名称+ID 形式),只是不能再从动作选择器一键添加。": "削除後も過去の記録は保持されます（名前+ID）。選択リストから追加できなくなるだけです。",

  // ---- 数据管理 ----
  "数据管理": "データ管理",
  "导出备份": "バックアップ出力",
  "导入恢复": "バックアップ復元",
  "建议备份": "バックアップ推奨",
  "尚未备份": "未バックアップ",
  "上次备份：{d}": "前回バックアップ：{d}",
  "导入将": "インポートすると",
  "覆盖当前全部数据": "現在の全データを上書き",
  "当前 {a} 天记录 → 替换为备份的 {b} 天": "現在{a}日分 → バックアップの{b}日分に置換",
  "确认覆盖导入": "上書きインポート確認",
  "清空全部数据": "全データを削除",
  "确认清空？不可恢复": "削除を確認？復元不可",
  "确认清空": "削除を確認",
  "数据仅保存在此设备的浏览器中。清理浏览器数据或更换设备前，请先导出备份。": "データはこの端末のブラウザのみに保存。ブラウザデータ削除や機種変更の前にバックアップを。",
  "导入成功，数据已恢复": "インポート成功。データを復元しました",
  "导入失败": "インポート失敗",
  "文件无法解析": "ファイルを解析できません",
  "文件格式不正确：不是 fitlog 备份": "形式が不正：fitlogのバックアップではありません",

  // ---- 肌群 / 器械 ----
  "胸": "胸",
  "背": "背中",
  "前束": "三角筋前部",
  "中束": "三角筋中部",
  "后束": "三角筋後部",
  "二头": "二頭筋",
  "三头": "三頭筋",
  "股四头": "四頭筋",
  "腘绳": "ハム",
  "臀": "臀筋",
  "小腿": "カーフ",
  "腹肌": "腹筋",
  "自由重量": "フリーウェイト",
  "器械": "マシン",
  "绳索": "ケーブル",
  "自重": "自重",

  // ---- 动作名 ----
  "上斜哑铃卧推": "インクラインダンベルプレス",
  "双杠臂屈伸": "ディップス",
  "绳索侧平举": "ケーブルサイドレイズ",
  "器械侧平举": "マシンサイドレイズ",
  "仰卧臂屈伸": "ライイングトライセプスエクステンション",
  "引体向上": "懸垂（チンニング）",
  "直臂下拉": "ストレートアームプルダウン",
  "杠铃划船": "ベントオーバーロウ",
  "牧师凳弯举": "プリーチャーカール",
  "深蹲": "スクワット",
  "保加利亚分腿蹲": "ブルガリアンスクワット",
  "罗马尼亚硬拉": "ルーマニアンデッドリフト",
  "坐姿腿弯举": "シーテッドレッグカール",
  "卷腹": "クランチ",
  "悬垂举腿": "ハンギングレッグレイズ",
  "绳索卷腹": "ケーブルクランチ",
  "下胸": "下部",
  "起始次数": "開始レップ",
  "力竭次数": "限界レップ",
  "斜方肌": "僧帽筋",
  "前锯肌": "前鋸筋",
  "前臂": "前腕",
  "内收肌": "内転筋",
  "外展肌": "外転筋",
  "颈部": "首",
  "其它": "その他",
  "清除": "クリア",
  "耸肩": "シュラッグ",
  "器械耸肩": "マシンシュラッグ",
  "直立划船": "アップライトロウ",
  "腕弯举": "リストカール",
  "反向腕弯举": "リバースリストカール",
  "前锯肌俯卧撑": "プッシュアッププラス",
  "绳索前推": "ケーブルパンチ",
  "坐姿夹腿": "アダクションマシン",
  "哥本哈根侧桥": "コペンハーゲンプランク",
  "绳索髋外展": "ケーブルアブダクション",
  "颈部前屈": "ネックフレクション",
  "颈部后伸": "ネックエクステンション",
  "坐姿推胸": "チェストプレス",
  "上斜推胸": "インクラインチェストプレス",
  "蝴蝶机夹胸": "ペックフライ",
  "绳索夹胸": "ケーブルフライ",
  "坐姿肩推": "ショルダープレス",
  "侧平举": "サイドレイズ",
  "三头下压": "トライセプスプッシュダウン",
  "过顶臂屈伸": "オーバーヘッドエクステンション",
  "高位下拉": "ラットプルダウン",
  "坐姿划船": "シーテッドロー",
  "对握下拉": "ナローグリップ・プルダウン",
  "反向蝴蝶机": "リアデルトフライ",
  "面拉": "フェイスプル",
  "二头弯举": "アームカール",
  "锤式弯举": "ハンマーカール",
  "腿举": "レッグプレス",
  "哈克深蹲": "ハックスクワット",
  "坐姿腿屈伸": "レッグエクステンション",
  "俯卧腿弯举": "ライイングレッグカール",
  "臀冲": "ヒップスラスト",
  "髋外展": "ヒップアブダクション",
  "提踵": "カーフレイズ",
  "中胸": "中部",
  "上胸": "上部",
  "阔背": "広背筋",
  "中背": "背中中部",

  "每类型可建多个模板（最多 5 个），自由命名；存组数×次数不存重量": "種類ごとに複数テンプレート作成可（最大5）。自由に命名。セット×回数を保存、重量は保存しない",
  "新建模板": "テンプレートを追加",
  "已达上限 5 个": "上限5に到達",
  "模板名称…": "テンプレート名…",
  "未命名模板": "名称未設定",
  "空模板": "空のテンプレート",
  "{n} 个模板": "テンプレート{n}件",
  // ---- 本周容量稽核（C） ----
  "本周容量": "今週のボリューム",
  "目标": "目標",
  "欠": "不足",
  "达标": "達成",
  "偏多": "多め",
  "设置训练水平后显示达标对照": "トレーニングレベルを設定すると達成度を表示",
  "先设训练水平 →": "レベルを設定 →",
  "本周还没有训练记录": "今週はまだトレーニング記録がありません",
  "按主肌群计，1 组 = 1 个动作的 1 组。仅统计已打标动作，旧记录可能少算。": "主働筋でカウント。1セット＝1種目の1セット。タグ付き種目のみ集計（古い記録は少なく出る場合あり）。",
  // ---- 日期 ----
  "昨天": "昨日",
  "刚刚": "たった今",
  "{n} 天前": "{n}日前",
  "周日": "日",
  "周一": "月",
  "周二": "火",
  "周三": "水",
  "周四": "木",
  "周五": "金",
  "周六": "土",

  // ---- 减脂 ----
  "减脂": "減量",
  "身高、生理性别与出生年份用于腰围 RFM 体脂和减脂能量估算，不影响训练建议。": "身長・生物学的性別・出生年は、ウエストRFM体脂肪と減量エネルギー推定に使用します。トレーニング提案には影響しません。",
};

export const DICT_EN: Record<string, string> = {
  // ---- 导航 / 通用 ----
  "今天": "Today",
  "今日": "Today",
  "计划": "Plan",
  "历史": "History",
  "数据": "Data",
  "设置": "Settings",
  "取消": "Cancel",
  "删除": "Delete",
  "记录": "Log",
  "编辑": "Edit",
  "切换": "Switch",
  "收起": "Close",
  "移除": "Remove",
  "上移": "Move up",
  "下移": "Move down",
  "选填": "Optional",
  "未设置": "Not set",
  "未分类": "Untagged",
  "未记录": "Not logged",
  "未规划": "None",
  "已记录": "Logged",
  "已加入": "Added",
  "已启用": "Active",
  "已保存": "Saved",
  "已清空": "Cleared",
  "已选定": "Selected",
  "新的一天": "A new day",
  "天": "days",
  "组": "sets",
  "次": "reps",
  "分": "min",
  "分钟": "min",
  "动作": "Exercise",
  "其他": "Other",
  "新建": "Add",
  "完成": "Done",
  "复制": "Copy",
  "复制全部计划": "Copy all plans",
  "已复制": "Copied",
  "复制失败，请手动选择": "Copy failed, please select manually",
  "分享": "Share",
  "今日卡片": "Today's card",
  "今天还没有记录": "Nothing logged today yet",
  "折叠": "Collapse",
  "刷新": "Reload",
  "有新版本": "Update available",

  // ---- 训练类型 ----
  "推": "Push",
  "拉": "Pull",
  "腿": "Legs",
  "休": "Rest",
  "休息": "Rest",
  "休息日": "Rest day",
  "自定义": "Custom",
  "推日": "Push Day",
  "拉日": "Pull Day",
  "腿日": "Leg Day",

  // ---- 首页 ----
  "训练": "Training",
  "饮食": "Nutrition",
  "有氧": "Cardio",
  "训练 · TRAINING": "TRAINING",
  "饮食 · NUTRITION": "NUTRITION",
  "有氧 · CARDIO": "CARDIO",
  "今日状态": "Today's status",
  "还未记录": "Not logged",
  "选择训练": "Choose training",
  "已记为休息日": "Logged as rest day",
  "点击编辑 →": "Tap to edit →",
  "点击查看 / 再记一条 →": "View / log another →",
  "待开始": "Not started",
  "还差训练": "Training pending",
  "还差饮食": "Nutrition pending",
  "{n} 组完成 · 查看 →": "{n} sets done · View →",
  "已完成 {n} 组 · 继续 →": "{n} sets · Resume →",
  "今日计划 · {s} →": "Planned · {s} →",
  "{n} 组": "{n} sets",
  "进行中": "Active",
  "开始训练": "Start session",
  "开始记录": "Start logging",
  "继续": "Resume",
  "训练已完成": "Session completed",
  "今日已完成": "All done today",
  "连续": "Streak",
  "记录有氧": "Log cardio",
  "沿用上次": "Use last",
  "已加一组": "Set added",

  // ---- 训练页 / 模块 ----
  "补记训练": "Edit past training",
  "选择今天的训练类型开始记录": "Pick today's training type to start",
  "休息日 · 好好恢复": "Rest day · Recover well",
  "结束训练": "Finish session",
  "继续记录": "Keep logging",
  "切到休息日？已记录的 {n} 组会被隐藏": "Switch to rest? Your {n} logged sets will be hidden",
  "切到「{t}」？已记录的 {n} 组会保留": "Switch to {t}? Your {n} logged sets will be kept",
  "数据不会删除": "Nothing gets deleted",
  "，切回原类型即可见": " — switch back to see them",
  "已套用 {a} · +{n} 动作": "Applied {a} · +{n} exercises",
  "动作已都在": "All exercises already added",
  "编辑模板": "Edit templates",
  "· 补记": "· Backfill",

  // ---- 动作卡 ----
  "主": "MAIN",
  "计划 {p}": "Plan {p}",
  "上次": "Last",
  "上次 ": "Last ",
  "首次记录此动作": "First time logging this",
  "空白组": "Empty set",
  "加一组": "Add set",
  "删除动作": "Delete exercise",
  "删除该组": "Delete set",
  "删除「{name}」及 {n} 组记录？": "Delete \u201c{name}\u201d and its {n} sets?",
  "第{n}组 重量": "Set {n} weight",
  "第{n}组 次数": "Set {n} reps",
  "减一组": "Fewer sets",

  // ---- 添加动作面板 ----
  "添加动作": "Add exercise",
  "上次也做了": "From last session",
  "+ 全部加入": "+ Add all",
  "新建动作名称…": "New exercise name…",
  "选部位": "Muscle",
  "没有想要的？新建「{m}」动作": "Missing one? Create a {m} exercise",
  "动作名称…": "Exercise name…",
  "已删除": "Deleted",
  "已移到 {m}": "Moved to {m}",
  "删除后历史记录仍保留，模板里若引用会保留名字但不再按部位归类。": "History is kept after delete. If used in a template the name stays, but it's no longer grouped by muscle.",
  "点铅笔可改名 / 改部位 / 改器械或删除。删除后历史记录仍保留，只是不再出现在选择器。": "Tap the pencil to rename / change muscle / equipment or delete. History stays after delete; it just leaves the picker.",
  "器械（选填）": "Equipment (opt.)",
  "选好部位，这个动作才会计入容量统计、并能按部位找到": "Pick a muscle so it counts toward volume and is findable by muscle",
  "已有记录，删除请到该动作卡片": "Has logged sets — delete from its card",

  // ---- 模板 ----
  "训练模板": "Training templates",
  "推 1": "Push 1",
  "推 2": "Push 2",
  "拉 1": "Pull 1",
  "拉 2": "Pull 2",
  "如：重量向": "e.g. heavy",
  "如：容量向": "e.g. volume",
  "如：宽度向": "e.g. width",
  "如：厚度向": "e.g. thickness",
  "一份即可": "one is enough",
  "推1 / 推2 / 拉1 / 拉2 / 腿": "Push 1/2 · Pull 1/2 · Legs",
  "按部位选动作 · 存目标组数×次数 · 训练页一键套用": "Pick by muscle · target sets × reps · one-tap apply",
  "存动作与目标组数 × 次数，不存重量 —— 重量由「沿用上次」自动跟随": "Stores exercises and target sets × reps. No weights — those follow your last session automatically",
  "{n} 动作 · {m} 组": "{n} exercises · {m} sets",
  "{n}/5 已设": "{n}/5 set",
  "还没有动作 —— 从下方按部位添加": "No exercises yet — add by muscle below",
  "组 ×": "sets ×",
  "按部位加动作": "Add by muscle",
  "按部位选择": "Pick by muscle",
  "这个部位还没有动作": "No exercises for this muscle yet",

  // ---- 营养 ----
  "营养": "Nutrition",
  "快速": "Quick",
  "详细": "Detail",
  "热量": "Calories",
  "蛋白": "Protein",
  "碳水": "Carbs",
  "脂肪": "Fat",
  "补记饮食": "Edit past nutrition",
  "继承上次 {n} kcal · 一键填入": "Use last {n} kcal · one tap",
  "复制上次 · {n} kcal": "Copy last · {n} kcal",
  "宏量按昨天比例自动估算": "Macros estimated from last ratio",
  "宏量按默认比例估算 · P30/C45/F25": "Macros by default ratio · P30/C45/F25",
  "输入热量即可，宏量自动生成": "Enter calories — macros auto-fill",
  "宏量推算约 {n} kcal，与录入差距较大（仅提醒）": "Macros imply ~{n} kcal — big gap vs entry (FYI)",
  "微调宏量": "Fine-tune macros",

  // ---- 有氧 ----
  "补记有氧": "Edit past cardio",
  "走路": "Walk",
  "跑步": "Run",
  "单车": "Bike",
  "椭圆机": "Elliptical",
  "划船": "Row",
  "爬楼梯": "Stairs",
  "跳绳": "Jump rope",
  "自定义方式（如：游泳、爬山）": "Custom (e.g. swim, hike)",
  "时长": "Duration",
  "时长（分钟）": "Duration (min)",
  "平均心率": "Avg HR",
  "平均心率（选填）": "Avg HR (optional)",
  "备注（选填）": "Note (optional)",
  "平均 {n} bpm": "avg {n} bpm",
  "已记录有氧": "Cardio logged",
  "填了身体数据后，平均心率可自动判定区间": "Add body data to auto-detect zone from avg HR",

  // ---- 心率区间 ----
  "心率区间": "Heart-rate zones",
  "· 选强度": "· pick intensity",
  "恢复": "Recovery",
  "有氧基础": "Base",
  "节奏": "Tempo",
  "阈值": "Threshold",
  "最大": "Max",
  "很轻松，能轻松交谈甚至唱歌": "Very easy — can chat or even sing",
  "能完整成句对话 · 燃脂主区": "Full sentences possible · fat-burn zone",
  "说话开始断续": "Speech gets choppy",
  "只能蹦出几个词 · 间歇": "Only a few words · intervals",
  "几乎说不出话 · 冲刺": "Can barely speak · sprints",
  "凭感觉": "by feel",
  "填身体数据 →": "Add body data →",
  "区间为参考，非医疗建议": "Zones are guidance, not medical advice",
  "填入年龄即可显示你的具体心率区间": "Enter your age to see exact bpm zones",
  "基于实测最大心率 {bpm} + 静息心率（Karvonen）": "From measured max HR {bpm} + resting HR (Karvonen)",
  "基于实测最大心率 {bpm}": "From measured max HR {bpm}",
  "估算最大心率 {bpm} + 静息心率（Karvonen）· 估算值": "Est. max HR {bpm} + resting HR (Karvonen) · estimate",
  "估算最大心率 {bpm}（按年龄）· 个体可差 ±10–12 bpm": "Est. max HR {bpm} (by age) · individual ±10–12 bpm",

  // ---- 排程 ----
  "训练规划": "Training plan",
  "每周排程": "Weekly schedule",
  "训练状态": "Status",
  "推 / 拉 / 腿 / 休 / 无规划。改动即保存,只是建议,不约束实际训练。": "Push / Pull / Legs / Rest / None. Saves instantly. A suggestion only — never restricts logging.",
  "近 28 天": "Last 28 days",
  "近 4 周训练 {n} 天,可考虑安排减载(信息提示,不强制)": "{n} training days in 4 weeks — consider a deload (info only)",
  "近 4 周训练 {n} 天 —— 仅作参考,不做训练建议": "{n} training days in 4 weeks — reference only",
  "次训练": "sessions",
  "· 今": "· today",
  "一": "Mon",
  "二": "Tue",
  "三": "Wed",
  "四": "Thu",
  "五": "Fri",
  "六": "Sat",
  "日": "Sun",

  // ---- 历史 ----
  "近 30 天": "Last 30 days",
  "练": "Trained",
  "无训练": "No training",
  "改训练": "Training",
  "改饮食": "Nutrition",
  "改有氧": "Cardio",
  "有氧 {n}′": "Cardio {n}′",
  "未标强度 {n} 分钟": "No zone · {n} min",

  // ---- 数据页 ----
  "体重": "Body weight",
  "腰围与体脂": "Waist & body fat",
  "估算体脂率": "Estimated body fat",
  "仅作估算": "Estimate only",
  "先在设置填写生理性别和身高": "Add biological sex and height in Settings first",
  "记录一条腰围后即可估算": "Log one waist entry to estimate",
  "前往设置": "Go to Settings",
  "腰围": "Waist",
  "用于 RFM": "Used for RFM",
  "腰高比": "Waist-to-height",
  "估算脂肪量": "Est. fat mass",
  "估算去脂体重": "Est. lean mass",
  "由体重换算": "Converted from weight",
  "再记录体重后，可换算估算脂肪量与去脂体重": "Log body weight to convert estimated fat and lean mass",
  "公式：{formula}。体重仅用于换算脂肪量，不参与体脂公式。": "Formula: {formula}. Weight only converts fat mass; it is not part of the body-fat formula.",
  "腰围测量标准": "Waist measurement protocol",
  "站立、自然呼气末、皮尺水平贴在裸露腰部右侧髂嵴最高外缘；不勒紧。每次尽量同一时间和位置。": "Stand upright. At the end of a normal exhale, place the tape horizontally on bare skin at the uppermost lateral border of the right ilium. Do not cinch; use the same time and site each time.",
  "RFM 适用于成人群体估算；肌肉量极高、特殊疾病或测量位置变化时偏差会更大。优先看同一测量方法下的长期趋势。": "RFM is an adult-population estimate. Error can be larger with very high muscularity, certain diseases, or a changed measurement site. Prioritize long-term trends measured the same way.",
  "还没有腰围记录": "No waist entries yet",
  "腰围趋势图：{range}，共 {n} 条记录": "Waist trend: {range}, {n} entries",
  "今日腰围": "Today's waist",
  "今日体重": "Today's weight",
  "记录今天": "Log today",
  "今天已记录，可覆盖": "Logged today — can overwrite",
  "趋势与备份": "Trend & backup",
  "本周有氧 · 7 天": "Cardio this week · 7 days",
  "近期训练": "Recent sessions",
  "还没有训练记录": "No sessions yet",
  "本周平均": "This week avg",
  "均线": "Avg line",
  "基于 {n} 次": "from {n} entries",
  "{n}周前": "{n}w ago",
  "对比": "Compare",
  "{n}周前平均": "{n}w ago avg",
  "该周暂无记录，数据不足以对比": "No records that week, not enough to compare",
  "轻了 {n} kg": "down {n} kg",
  "重了 {n} kg": "up {n} kg",
  "还没有体重记录": "No weight entries yet",
  "近 {n} 次": "last {n}",
  "近 {n} 天": "last {n} days",
  "全部": "All",
  "图表范围": "Chart range",
  "点按图表查看": "Tap chart to inspect",
  "{n} 条": "{n} entries",
  "体重趋势图：{range}，共 {n} 条记录": "Weight trend: {range}, {n} entries",
  "较上一条": "vs previous",
  "首条记录": "First entry",
  "查看全部 {n} 条": "Show all {n}",
  "收起记录": "Collapse entries",
  "仅显示，不可编辑": "View only",

  // ---- 设置 ----
  "偏好 · 数据 · 备份": "Preferences · data · backup",
  "界面模式": "UI mode",
  "默认": "Default",
  "纯工具感": "Pure tool",
  "更强反馈与节奏感": "Stronger feedback & rhythm",
  "模式只改变视觉与微反馈,不改变数据。随时切换。": "Mode changes visuals and micro-feedback only — never data. Switch anytime.",
  "语言": "Language",
  "身体数据": "Body data",
  "身高": "Height",
  "生理性别": "Biological sex",
  "男性": "Male",
  "女性": "Female",
  "身高和生理性别仅用于腰围 RFM 体脂估算，不影响训练建议。": "Height and biological sex are used only for waist-based RFM body-fat estimation; they do not affect training guidance.",
  "出生年份": "Birth year",
  "如 2003": "e.g. 2003",
  "静息心率": "Resting HR",
  "最大心率": "Max HR",
  "推算最大心率": "Estimated max HR",
  "全部可选 —— 不填也能用谈话测试估区间；填了越多，心率区间越贴你。静息心率：早晨醒来别动，数 1 分钟脉搏。": "All optional — without data the talk test still works; more data, more accurate zones. Resting HR: count your pulse for 1 min right after waking.",
  "训练水平": "Training level",
  "新手": "Beginner",
  "中级": "Intermediate",
  "高级": "Advanced",
  "< 1 年": "< 1 yr",
  "1 – 3 年": "1–3 yrs",
  "3 年以上": "3+ yrs",
  "较低容量即可进步，过量反而恢复不来": "Grows on low volume; more just hurts recovery",
  "需要更高容量维持进步": "Needs more volume to keep progressing",
  "接近容量上限，注重质量与恢复": "Near volume ceiling — quality and recovery first",
  "每周每肌群目标": "Weekly target per muscle",
  "选择训练水平，系统给出适合你的每周容量目标（新手不必硬上大容量）。": "Pick your level to get a fitting weekly volume target (beginners don't need huge volume).",
  "小肌群（二头/三头/小腿）通常还会从复合动作获得额外间接容量。区间为参考，按恢复情况自行增减。": "Small muscles (biceps/triceps/calves) also get indirect volume from compounds. Adjust by recovery.",
  "自定义动作": "Custom exercises",
  "确认删除": "Confirm delete",
  "删除后,以前记录里的该动作仍然保留(以名称+ID 形式),只是不能再从动作选择器一键添加。": "Past logs keep this exercise (name + ID); it just disappears from the picker.",

  // ---- 数据管理 ----
  "数据管理": "Data",
  "导出备份": "Export backup",
  "导入恢复": "Import backup",
  "建议备份": "Backup advised",
  "尚未备份": "Never backed up",
  "上次备份：{d}": "Last backup: {d}",
  "导入将": "Import will ",
  "覆盖当前全部数据": "overwrite all current data",
  "当前 {a} 天记录 → 替换为备份的 {b} 天": "Current {a} days → replaced by backup's {b} days",
  "确认覆盖导入": "Confirm overwrite",
  "清空全部数据": "Erase all data",
  "确认清空？不可恢复": "Erase everything? Irreversible",
  "确认清空": "Confirm erase",
  "数据仅保存在此设备的浏览器中。清理浏览器数据或更换设备前，请先导出备份。": "Data lives only in this browser. Export a backup before clearing browser data or switching devices.",
  "导入成功，数据已恢复": "Imported — data restored",
  "导入失败": "Import failed",
  "文件无法解析": "Can't parse file",
  "文件格式不正确：不是 fitlog 备份": "Invalid format: not a fitlog backup",

  // ---- 肌群 / 器械 ----
  "胸": "Chest",
  "背": "Back",
  "前束": "Front delt",
  "中束": "Side delt",
  "后束": "Rear delt",
  "二头": "Biceps",
  "三头": "Triceps",
  "股四头": "Quads",
  "腘绳": "Hams",
  "臀": "Glutes",
  "小腿": "Calves",
  "腹肌": "Abs",
  "自由重量": "Free weight",
  "器械": "Machine",
  "绳索": "Cable",
  "自重": "Bodyweight",

  // ---- 动作名 ----
  "上斜哑铃卧推": "Incline Dumbbell Press",
  "双杠臂屈伸": "Dips",
  "绳索侧平举": "Cable Lateral Raise",
  "器械侧平举": "Machine Lateral Raise",
  "仰卧臂屈伸": "Lying Triceps Extension",
  "引体向上": "Pull-up",
  "直臂下拉": "Straight-Arm Pulldown",
  "杠铃划船": "Barbell Row",
  "牧师凳弯举": "Preacher Curl",
  "深蹲": "Squat",
  "保加利亚分腿蹲": "Bulgarian Split Squat",
  "罗马尼亚硬拉": "Romanian Deadlift",
  "坐姿腿弯举": "Seated Leg Curl",
  "卷腹": "Crunch",
  "悬垂举腿": "Hanging Leg Raise",
  "绳索卷腹": "Cable Crunch",
  "下胸": "lower chest",
  "起始次数": "Start reps",
  "力竭次数": "Failure reps",
  "斜方肌": "Traps",
  "前锯肌": "Serratus",
  "前臂": "Forearms",
  "内收肌": "Adductors",
  "外展肌": "Abductors",
  "颈部": "Neck",
  "其它": "Other",
  "清除": "Clear",
  "耸肩": "Shrug",
  "器械耸肩": "Machine Shrug",
  "直立划船": "Upright Row",
  "腕弯举": "Wrist Curl",
  "反向腕弯举": "Reverse Wrist Curl",
  "前锯肌俯卧撑": "Push-up Plus",
  "绳索前推": "Cable Punch",
  "坐姿夹腿": "Seated Adduction",
  "哥本哈根侧桥": "Copenhagen Plank",
  "绳索髋外展": "Cable Abduction",
  "颈部前屈": "Neck Flexion",
  "颈部后伸": "Neck Extension",
  "坐姿推胸": "Chest Press",
  "上斜推胸": "Incline Chest Press",
  "蝴蝶机夹胸": "Pec Deck Fly",
  "绳索夹胸": "Cable Fly",
  "坐姿肩推": "Shoulder Press",
  "侧平举": "Lateral Raise",
  "三头下压": "Triceps Pushdown",
  "过顶臂屈伸": "Overhead Extension",
  "高位下拉": "Lat Pulldown",
  "坐姿划船": "Seated Row",
  "对握下拉": "Close-Grip Pulldown",
  "反向蝴蝶机": "Reverse Pec Deck",
  "面拉": "Face Pull",
  "二头弯举": "Biceps Curl",
  "锤式弯举": "Hammer Curl",
  "腿举": "Leg Press",
  "哈克深蹲": "Hack Squat",
  "坐姿腿屈伸": "Leg Extension",
  "俯卧腿弯举": "Lying Leg Curl",
  "臀冲": "Hip Thrust",
  "髋外展": "Hip Abduction",
  "提踵": "Calf Raise",
  "中胸": "mid chest",
  "上胸": "upper chest",
  "阔背": "lats",
  "中背": "mid back",

  "每类型可建多个模板（最多 5 个），自由命名；存组数×次数不存重量": "Multiple templates per type (max 5), freely named; stores sets×reps, not weight",
  "新建模板": "New template",
  "已达上限 5 个": "Max 5 reached",
  "模板名称…": "Template name…",
  "未命名模板": "Untitled",
  "空模板": "Empty template",
  "{n} 个模板": "{n} templates",
  // ---- 本周容量稽核（C） ----
  "本周容量": "Volume this week",
  "目标": "Target",
  "欠": "Low",
  "达标": "On target",
  "偏多": "High",
  "设置训练水平后显示达标对照": "Set your training level to see target status",
  "先设训练水平 →": "Set level →",
  "本周还没有训练记录": "No training logged this week yet",
  "按主肌群计，1 组 = 1 个动作的 1 组。仅统计已打标动作，旧记录可能少算。": "Counts primary muscle; 1 set = one set of one exercise. Tagged exercises only (older logs may undercount).",
  // ---- 日期 ----
  "昨天": "Yesterday",
  "刚刚": "just now",
  "{n} 天前": "{n}d ago",
  "周日": "Sun",
  "周一": "Mon",
  "周二": "Tue",
  "周三": "Wed",
  "周四": "Thu",
  "周五": "Fri",
  "周六": "Sat",
  // ---- Cut ----
  "减脂": "Cut",
  "身高、生理性别与出生年份用于腰围 RFM 体脂和减脂能量估算，不影响训练建议。": "Height, biological sex and birth year are used for RFM and cutting-energy estimates; they do not change training advice.",

};
