export type SystemTextLocale = "zh" | "ja" | "en";

type LocalizedText = Record<SystemTextLocale, string>;

const EXACT_SYSTEM_TEXT: Record<string, LocalizedText> = {
  Push: { zh: "推", en: "Push", ja: "プッシュ" },
  Pull: { zh: "拉", en: "Pull", ja: "プル" },
  Legs: { zh: "腿", en: "Legs", ja: "脚" },
  Rest: { zh: "休息", en: "Rest", ja: "休息" },
  "Push Strength": { zh: "推 · 力量", en: "Push strength", ja: "プッシュ・筋力" },
  "Pull Strength": { zh: "拉 · 力量", en: "Pull strength", ja: "プル・筋力" },
  "Legs Strength": { zh: "腿 · 力量", en: "Leg strength", ja: "脚・筋力" },
  "Push Hypertrophy": { zh: "推 · 增肌", en: "Push hypertrophy", ja: "プッシュ・筋肥大" },
  "Pull Hypertrophy": { zh: "拉 · 增肌", en: "Pull hypertrophy", ja: "プル・筋肥大" },
  "Legs Hypertrophy": { zh: "腿 · 增肌", en: "Leg hypertrophy", ja: "脚・筋肥大" },
  "推 · 基础": { zh: "推 · 基础", en: "Push · Base", ja: "プッシュ・基礎" },
  "拉 · 基础": { zh: "拉 · 基础", en: "Pull · Base", ja: "プル・基礎" },
  "腿 · 基础": { zh: "腿 · 基础", en: "Legs · Base", ja: "脚・基礎" },
  "推 · 力量": { zh: "推 · 力量", en: "Push · Strength", ja: "プッシュ・筋力" },
  "拉 · 力量": { zh: "拉 · 力量", en: "Pull · Strength", ja: "プル・筋力" },
  "腿 · 综合": { zh: "腿 · 综合", en: "Legs · Mixed", ja: "脚・総合" },
  "推 · 增肌": { zh: "推 · 增肌", en: "Push · Hypertrophy", ja: "プッシュ・筋肥大" },
  "拉 · 增肌": { zh: "拉 · 增肌", en: "Pull · Hypertrophy", ja: "プル・筋肥大" },
  "腿 · 力量": { zh: "腿 · 力量", en: "Legs · Strength", ja: "脚・筋力" },
  "腿 · 增肌": { zh: "腿 · 增肌", en: "Legs · Hypertrophy", ja: "脚・筋肥大" },
  "下背/竖脊肌": { zh: "下背/竖脊肌", en: "Lower back", ja: "下背部・脊柱起立筋" },
  "旧记录参考": { zh: "旧记录参考", en: "Legacy reference", ja: "旧記録の参考" },
  超: { zh: "超", en: "Over", ja: "超過" },
};

const INTENT: Record<string, LocalizedText> = {
  力量: { zh: "力量", en: "Strength", ja: "筋力" },
  增肌: { zh: "增肌", en: "Hypertrophy", ja: "筋肥大" },
  耐力: { zh: "耐力", en: "Endurance", ja: "持久力" },
  自定义: { zh: "自定义", en: "Custom", ja: "カスタム" },
  时长: { zh: "时长", en: "Duration", ja: "時間" },
  距离: { zh: "距离", en: "Distance", ja: "距離" },
};

const UNIT: Record<string, LocalizedText> = {
  次: { zh: "次", en: "reps", ja: "回" },
  秒: { zh: "秒", en: "sec", ja: "秒" },
  米: { zh: "米", en: "m", ja: "m" },
};

const GENERATED_TRACK_PATTERN = /^(力量|增肌|耐力|自定义|时长|距离) · (\d+(?:\.\d+)?)–(\d+(?:\.\d+)?) (次|秒|米)( · 独立)?$/;

/** Translates only labels generated by FitLog. User-authored text is returned untouched. */
export function localizeSystemText(locale: SystemTextLocale, source: string): string | undefined {
  const exact = EXACT_SYSTEM_TEXT[source];
  if (exact) return exact[locale];

  if (source.startsWith("恢复 · ")) {
    const inner = localizeSystemText(locale, source.slice("恢复 · ".length));
    if (!inner) return undefined;
    if (locale === "en") return `Recovery · ${inner}`;
    if (locale === "ja") return `回復 · ${inner}`;
    return `恢复 · ${inner}`;
  }

  const match = source.match(GENERATED_TRACK_PATTERN);
  if (!match) return undefined;
  const [, intent, minimum, maximum, unit, isolated] = match;
  const suffix = isolated
    ? locale === "en" ? " · independent" : locale === "ja" ? "・独立" : " · 独立"
    : "";
  return `${INTENT[intent][locale]} · ${minimum}–${maximum} ${UNIT[unit][locale]}${suffix}`;
}
